# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shd < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-shd"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.4.0/shd_0.4.0_darwin_amd64.tar.gz"
      sha256 "f496ea70f69ece5e8ad3f95efaa0de4e8c644b9c3d6f1d8e34b6cc48607aac63"

      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.4.0/shd_0.4.0_darwin_arm64.tar.gz"
      sha256 "c29458410981196a040d0278182286a6c17aafe3de3a6268d2e7c2efb15a1ad8"

      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.4.0/shd_0.4.0_linux_amd64.tar.gz"
      sha256 "98bfa48678511cfcd5e6894bc4ce3a33e0c8a6d6beb3d4036ea076c0c5b495f8"
      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.4.0/shd_0.4.0_linux_arm64.tar.gz"
      sha256 "782f5032758727a8b0dbaff59d8d7d751d70865d987421b93316cca131c27ee9"
      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  test do
    assert_match "shd", shell_output("#{bin}/shd version")
  end
end
