# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shd < Formula
  desc "Generate split-horizon DNS (Pi-hole/dnsmasq) and Caddy site blocks from a declarative services.yaml"
  homepage "https://github.com/Miista/homebrew-shd"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.7.0/shd_0.7.0_darwin_amd64.tar.gz"
      sha256 "b45ee25be511a3b49cef37d1c6485ece67ec5dbbe32834ab99d27160bf44b907"

      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.7.0/shd_0.7.0_darwin_arm64.tar.gz"
      sha256 "c6f1afb5d759cad32f46ad73794a10260a7ac29897157aac7e935eb42e366b54"

      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.7.0/shd_0.7.0_linux_amd64.tar.gz"
      sha256 "841eeb3ddc95532eef1c164b81c2ddfb51fafbc8dde82d6268f8564aee9d1205"
      define_method(:install) do
        bin.install "shd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Miista/homebrew-shd/releases/download/v0.7.0/shd_0.7.0_linux_arm64.tar.gz"
      sha256 "24f28bc908932a7205b678722cd697f2b633365023737958cf6c9ec3728cb4ae"
      define_method(:install) do
        bin.install "shd"
      end
    end
  end

  test do
    assert_match "shd", shell_output("#{bin}/shd version")
  end
end
